/* eslint-disable max-lines */
/**
 * Auto-generated by scripts/generate-countries.mjs — do not edit by hand.
 * Priority block (Americas + Spain + Brazil + Canada) uses curated symbols.
 */

export type CountryRecord = {
  /** ISO 3166-1 alpha-2 */
  code: string;
  nameEn: string;
  nameEs: string;
  /** ISO 4217 */
  currencyCode: string;
  currencySymbol: string;
  currencyNameEn: string;
  currencyNameEs: string;
};

export const COUNTRIES: CountryRecord[] = [
  {
    "code": "US",
    "nameEn": "United States",
    "nameEs": "Estados Unidos",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "US Dollar",
    "currencyNameEs": "Dólar estadounidense"
  },
  {
    "code": "MX",
    "nameEn": "Mexico",
    "nameEs": "México",
    "currencyCode": "MXN",
    "currencySymbol": "$",
    "currencyNameEn": "Mexican Peso",
    "currencyNameEs": "Peso mexicano"
  },
  {
    "code": "PR",
    "nameEn": "Puerto Rico",
    "nameEs": "Puerto Rico",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "US Dollar",
    "currencyNameEs": "Dólar estadounidense"
  },
  {
    "code": "HN",
    "nameEn": "Honduras",
    "nameEs": "Honduras",
    "currencyCode": "HNL",
    "currencySymbol": "L",
    "currencyNameEn": "Honduran Lempira",
    "currencyNameEs": "Lempira hondureña"
  },
  {
    "code": "CO",
    "nameEn": "Colombia",
    "nameEs": "Colombia",
    "currencyCode": "COP",
    "currencySymbol": "$",
    "currencyNameEn": "Colombian Peso",
    "currencyNameEs": "Peso colombiano"
  },
  {
    "code": "VE",
    "nameEn": "Venezuela",
    "nameEs": "Venezuela",
    "currencyCode": "VES",
    "currencySymbol": "Bs.S",
    "currencyNameEn": "Venezuelan Bolívar",
    "currencyNameEs": "Bolívar venezolano"
  },
  {
    "code": "GT",
    "nameEn": "Guatemala",
    "nameEs": "Guatemala",
    "currencyCode": "GTQ",
    "currencySymbol": "Q",
    "currencyNameEn": "Guatemalan Quetzal",
    "currencyNameEs": "Quetzal guatemalteco"
  },
  {
    "code": "SV",
    "nameEn": "El Salvador",
    "nameEs": "El Salvador",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "US Dollar",
    "currencyNameEs": "Dólar estadounidense"
  },
  {
    "code": "DO",
    "nameEn": "Dominican Republic",
    "nameEs": "República Dominicana",
    "currencyCode": "DOP",
    "currencySymbol": "RD$",
    "currencyNameEn": "Dominican Peso",
    "currencyNameEs": "Peso dominicano"
  },
  {
    "code": "CU",
    "nameEn": "Cuba",
    "nameEs": "Cuba",
    "currencyCode": "CUP",
    "currencySymbol": "₱",
    "currencyNameEn": "Cuban Peso",
    "currencyNameEs": "Peso cubano"
  },
  {
    "code": "PE",
    "nameEn": "Peru",
    "nameEs": "Perú",
    "currencyCode": "PEN",
    "currencySymbol": "S/.",
    "currencyNameEn": "Peruvian Sol",
    "currencyNameEs": "Sol peruano"
  },
  {
    "code": "CL",
    "nameEn": "Chile",
    "nameEs": "Chile",
    "currencyCode": "CLP",
    "currencySymbol": "$",
    "currencyNameEn": "Chilean Peso",
    "currencyNameEs": "Peso chileno"
  },
  {
    "code": "AR",
    "nameEn": "Argentina",
    "nameEs": "Argentina",
    "currencyCode": "ARS",
    "currencySymbol": "$",
    "currencyNameEn": "Argentine Peso",
    "currencyNameEs": "Peso argentino"
  },
  {
    "code": "BO",
    "nameEn": "Bolivia",
    "nameEs": "Bolivia",
    "currencyCode": "BOB",
    "currencySymbol": "Bs.",
    "currencyNameEn": "Bolivian Boliviano",
    "currencyNameEs": "Boliviano"
  },
  {
    "code": "EC",
    "nameEn": "Ecuador",
    "nameEs": "Ecuador",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "US Dollar",
    "currencyNameEs": "Dólar estadounidense"
  },
  {
    "code": "CR",
    "nameEn": "Costa Rica",
    "nameEs": "Costa Rica",
    "currencyCode": "CRC",
    "currencySymbol": "₡",
    "currencyNameEn": "Costa Rican Colón",
    "currencyNameEs": "Colón costarricense"
  },
  {
    "code": "PA",
    "nameEn": "Panama",
    "nameEs": "Panamá",
    "currencyCode": "PAB",
    "currencySymbol": "B/.",
    "currencyNameEn": "Panamanian Balboa",
    "currencyNameEs": "Balboa panameño"
  },
  {
    "code": "PY",
    "nameEn": "Paraguay",
    "nameEs": "Paraguay",
    "currencyCode": "PYG",
    "currencySymbol": "₲",
    "currencyNameEn": "Paraguayan Guaraní",
    "currencyNameEs": "Guaraní paraguayo"
  },
  {
    "code": "UY",
    "nameEn": "Uruguay",
    "nameEs": "Uruguay",
    "currencyCode": "UYU",
    "currencySymbol": "$U",
    "currencyNameEn": "Uruguayan Peso",
    "currencyNameEs": "Peso uruguayo"
  },
  {
    "code": "NI",
    "nameEn": "Nicaragua",
    "nameEs": "Nicaragua",
    "currencyCode": "NIO",
    "currencySymbol": "C$",
    "currencyNameEn": "Nicaraguan Córdoba",
    "currencyNameEs": "Córdoba nicaragüense"
  },
  {
    "code": "ES",
    "nameEn": "Spain",
    "nameEs": "España",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "Euro",
    "currencyNameEs": "Euro"
  },
  {
    "code": "BR",
    "nameEn": "Brazil",
    "nameEs": "Brasil",
    "currencyCode": "BRL",
    "currencySymbol": "R$",
    "currencyNameEn": "Brazilian Real",
    "currencyNameEs": "Real brasileño"
  },
  {
    "code": "CA",
    "nameEn": "Canada",
    "nameEs": "Canadá",
    "currencyCode": "CAD",
    "currencySymbol": "$",
    "currencyNameEn": "Canadian Dollar",
    "currencyNameEs": "Dólar canadiense"
  },
  {
    "code": "AF",
    "nameEn": "Afghanistan",
    "nameEs": "Afganistán",
    "currencyCode": "AFN",
    "currencySymbol": "؋",
    "currencyNameEn": "Afghan afghani",
    "currencyNameEs": "Afghan afghani"
  },
  {
    "code": "AX",
    "nameEn": "Åland Islands",
    "nameEs": "Alandia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "AL",
    "nameEn": "Albania",
    "nameEs": "Albania",
    "currencyCode": "ALL",
    "currencySymbol": "L",
    "currencyNameEn": "Albanian lek",
    "currencyNameEs": "Albanian lek"
  },
  {
    "code": "DZ",
    "nameEn": "Algeria",
    "nameEs": "Argelia",
    "currencyCode": "DZD",
    "currencySymbol": "د.ج",
    "currencyNameEn": "Algerian dinar",
    "currencyNameEs": "Algerian dinar"
  },
  {
    "code": "AS",
    "nameEn": "American Samoa",
    "nameEs": "Samoa Americana",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "AD",
    "nameEn": "Andorra",
    "nameEs": "Andorra",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "AO",
    "nameEn": "Angola",
    "nameEs": "Angola",
    "currencyCode": "AOA",
    "currencySymbol": "Kz",
    "currencyNameEn": "Angolan kwanza",
    "currencyNameEs": "Angolan kwanza"
  },
  {
    "code": "AI",
    "nameEn": "Anguilla",
    "nameEs": "Anguilla",
    "currencyCode": "XCD",
    "currencySymbol": "$",
    "currencyNameEn": "Eastern Caribbean dollar",
    "currencyNameEs": "Eastern Caribbean dollar"
  },
  {
    "code": "AQ",
    "nameEn": "Antarctica",
    "nameEs": "Antártida",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "US Dollar",
    "currencyNameEs": "Dólar estadounidense"
  },
  {
    "code": "AG",
    "nameEn": "Antigua and Barbuda",
    "nameEs": "Antigua y Barbuda",
    "currencyCode": "XCD",
    "currencySymbol": "$",
    "currencyNameEn": "Eastern Caribbean dollar",
    "currencyNameEs": "Eastern Caribbean dollar"
  },
  {
    "code": "AM",
    "nameEn": "Armenia",
    "nameEs": "Armenia",
    "currencyCode": "AMD",
    "currencySymbol": "֏",
    "currencyNameEn": "Armenian dram",
    "currencyNameEs": "Armenian dram"
  },
  {
    "code": "AW",
    "nameEn": "Aruba",
    "nameEs": "Aruba",
    "currencyCode": "AWG",
    "currencySymbol": "ƒ",
    "currencyNameEn": "Aruban florin",
    "currencyNameEs": "Aruban florin"
  },
  {
    "code": "AU",
    "nameEn": "Australia",
    "nameEs": "Australia",
    "currencyCode": "AUD",
    "currencySymbol": "$",
    "currencyNameEn": "Australian dollar",
    "currencyNameEs": "Australian dollar"
  },
  {
    "code": "AT",
    "nameEn": "Austria",
    "nameEs": "Austria",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "AZ",
    "nameEn": "Azerbaijan",
    "nameEs": "Azerbaiyán",
    "currencyCode": "AZN",
    "currencySymbol": "₼",
    "currencyNameEn": "Azerbaijani manat",
    "currencyNameEs": "Azerbaijani manat"
  },
  {
    "code": "BS",
    "nameEn": "Bahamas",
    "nameEs": "Bahamas",
    "currencyCode": "BSD",
    "currencySymbol": "$",
    "currencyNameEn": "Bahamian dollar",
    "currencyNameEs": "Bahamian dollar"
  },
  {
    "code": "BH",
    "nameEn": "Bahrain",
    "nameEs": "Bahrein",
    "currencyCode": "BHD",
    "currencySymbol": ".د.ب",
    "currencyNameEn": "Bahraini dinar",
    "currencyNameEs": "Bahraini dinar"
  },
  {
    "code": "BD",
    "nameEn": "Bangladesh",
    "nameEs": "Bangladesh",
    "currencyCode": "BDT",
    "currencySymbol": "৳",
    "currencyNameEn": "Bangladeshi taka",
    "currencyNameEs": "Bangladeshi taka"
  },
  {
    "code": "BB",
    "nameEn": "Barbados",
    "nameEs": "Barbados",
    "currencyCode": "BBD",
    "currencySymbol": "$",
    "currencyNameEn": "Barbadian dollar",
    "currencyNameEs": "Barbadian dollar"
  },
  {
    "code": "BY",
    "nameEn": "Belarus",
    "nameEs": "Bielorrusia",
    "currencyCode": "BYN",
    "currencySymbol": "Br",
    "currencyNameEn": "Belarusian ruble",
    "currencyNameEs": "Belarusian ruble"
  },
  {
    "code": "BE",
    "nameEn": "Belgium",
    "nameEs": "Bélgica",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "BZ",
    "nameEn": "Belize",
    "nameEs": "Belice",
    "currencyCode": "BZD",
    "currencySymbol": "$",
    "currencyNameEn": "Belize dollar",
    "currencyNameEs": "Belize dollar"
  },
  {
    "code": "BJ",
    "nameEn": "Benin",
    "nameEs": "Benín",
    "currencyCode": "XOF",
    "currencySymbol": "Fr",
    "currencyNameEn": "West African CFA franc",
    "currencyNameEs": "West African CFA franc"
  },
  {
    "code": "BM",
    "nameEn": "Bermuda",
    "nameEs": "Bermudas",
    "currencyCode": "BMD",
    "currencySymbol": "$",
    "currencyNameEn": "Bermudian dollar",
    "currencyNameEs": "Bermudian dollar"
  },
  {
    "code": "BT",
    "nameEn": "Bhutan",
    "nameEs": "Bután",
    "currencyCode": "BTN",
    "currencySymbol": "Nu.",
    "currencyNameEn": "Bhutanese ngultrum",
    "currencyNameEs": "Bhutanese ngultrum"
  },
  {
    "code": "BA",
    "nameEn": "Bosnia and Herzegovina",
    "nameEs": "Bosnia y Herzegovina",
    "currencyCode": "BAM",
    "currencySymbol": "KM",
    "currencyNameEn": "Bosnia and Herzegovina convertible mark",
    "currencyNameEs": "Bosnia and Herzegovina convertible mark"
  },
  {
    "code": "BW",
    "nameEn": "Botswana",
    "nameEs": "Botswana",
    "currencyCode": "BWP",
    "currencySymbol": "P",
    "currencyNameEn": "Botswana pula",
    "currencyNameEs": "Botswana pula"
  },
  {
    "code": "BV",
    "nameEn": "Bouvet Island",
    "nameEs": "Isla Bouvet",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "US Dollar",
    "currencyNameEs": "Dólar estadounidense"
  },
  {
    "code": "IO",
    "nameEn": "British Indian Ocean Territory",
    "nameEs": "Territorio Británico del Océano Índico",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "VG",
    "nameEn": "British Virgin Islands",
    "nameEs": "Islas Vírgenes del Reino Unido",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "BN",
    "nameEn": "Brunei",
    "nameEs": "Brunei",
    "currencyCode": "BND",
    "currencySymbol": "$",
    "currencyNameEn": "Brunei dollar",
    "currencyNameEs": "Brunei dollar"
  },
  {
    "code": "BG",
    "nameEn": "Bulgaria",
    "nameEs": "Bulgaria",
    "currencyCode": "BGN",
    "currencySymbol": "лв",
    "currencyNameEn": "Bulgarian lev",
    "currencyNameEs": "Bulgarian lev"
  },
  {
    "code": "BF",
    "nameEn": "Burkina Faso",
    "nameEs": "Burkina Faso",
    "currencyCode": "XOF",
    "currencySymbol": "Fr",
    "currencyNameEn": "West African CFA franc",
    "currencyNameEs": "West African CFA franc"
  },
  {
    "code": "BI",
    "nameEn": "Burundi",
    "nameEs": "Burundi",
    "currencyCode": "BIF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Burundian franc",
    "currencyNameEs": "Burundian franc"
  },
  {
    "code": "KH",
    "nameEn": "Cambodia",
    "nameEs": "Camboya",
    "currencyCode": "KHR",
    "currencySymbol": "៛",
    "currencyNameEn": "Cambodian riel",
    "currencyNameEs": "Cambodian riel"
  },
  {
    "code": "CM",
    "nameEn": "Cameroon",
    "nameEs": "Camerún",
    "currencyCode": "XAF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Central African CFA franc",
    "currencyNameEs": "Central African CFA franc"
  },
  {
    "code": "CV",
    "nameEn": "Cape Verde",
    "nameEs": "Cabo Verde",
    "currencyCode": "CVE",
    "currencySymbol": "Esc",
    "currencyNameEn": "Cape Verdean escudo",
    "currencyNameEs": "Cape Verdean escudo"
  },
  {
    "code": "BQ",
    "nameEn": "Caribbean Netherlands",
    "nameEs": "Caribe Neerlandés",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "KY",
    "nameEn": "Cayman Islands",
    "nameEs": "Islas Caimán",
    "currencyCode": "KYD",
    "currencySymbol": "$",
    "currencyNameEn": "Cayman Islands dollar",
    "currencyNameEs": "Cayman Islands dollar"
  },
  {
    "code": "CF",
    "nameEn": "Central African Republic",
    "nameEs": "República Centroafricana",
    "currencyCode": "XAF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Central African CFA franc",
    "currencyNameEs": "Central African CFA franc"
  },
  {
    "code": "TD",
    "nameEn": "Chad",
    "nameEs": "Chad",
    "currencyCode": "XAF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Central African CFA franc",
    "currencyNameEs": "Central African CFA franc"
  },
  {
    "code": "CN",
    "nameEn": "China",
    "nameEs": "China",
    "currencyCode": "CNY",
    "currencySymbol": "¥",
    "currencyNameEn": "Chinese yuan",
    "currencyNameEs": "Chinese yuan"
  },
  {
    "code": "CX",
    "nameEn": "Christmas Island",
    "nameEs": "Isla de Navidad",
    "currencyCode": "AUD",
    "currencySymbol": "$",
    "currencyNameEn": "Australian dollar",
    "currencyNameEs": "Australian dollar"
  },
  {
    "code": "CC",
    "nameEn": "Cocos (Keeling) Islands",
    "nameEs": "Islas Cocos o Islas Keeling",
    "currencyCode": "AUD",
    "currencySymbol": "$",
    "currencyNameEn": "Australian dollar",
    "currencyNameEs": "Australian dollar"
  },
  {
    "code": "KM",
    "nameEn": "Comoros",
    "nameEs": "Comoras",
    "currencyCode": "KMF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Comorian franc",
    "currencyNameEs": "Comorian franc"
  },
  {
    "code": "CK",
    "nameEn": "Cook Islands",
    "nameEs": "Islas Cook",
    "currencyCode": "CKD",
    "currencySymbol": "$",
    "currencyNameEn": "Cook Islands dollar",
    "currencyNameEs": "Cook Islands dollar"
  },
  {
    "code": "HR",
    "nameEn": "Croatia",
    "nameEs": "Croacia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "CW",
    "nameEn": "Curaçao",
    "nameEs": "Curazao",
    "currencyCode": "ANG",
    "currencySymbol": "ƒ",
    "currencyNameEn": "Netherlands Antillean guilder",
    "currencyNameEs": "Netherlands Antillean guilder"
  },
  {
    "code": "CY",
    "nameEn": "Cyprus",
    "nameEs": "Chipre",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "CZ",
    "nameEn": "Czechia",
    "nameEs": "Chequia",
    "currencyCode": "CZK",
    "currencySymbol": "Kč",
    "currencyNameEn": "Czech koruna",
    "currencyNameEs": "Czech koruna"
  },
  {
    "code": "DK",
    "nameEn": "Denmark",
    "nameEs": "Dinamarca",
    "currencyCode": "DKK",
    "currencySymbol": "kr",
    "currencyNameEn": "Danish krone",
    "currencyNameEs": "Danish krone"
  },
  {
    "code": "DJ",
    "nameEn": "Djibouti",
    "nameEs": "Djibouti",
    "currencyCode": "DJF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Djiboutian franc",
    "currencyNameEs": "Djiboutian franc"
  },
  {
    "code": "DM",
    "nameEn": "Dominica",
    "nameEs": "Dominica",
    "currencyCode": "XCD",
    "currencySymbol": "$",
    "currencyNameEn": "Eastern Caribbean dollar",
    "currencyNameEs": "Eastern Caribbean dollar"
  },
  {
    "code": "CD",
    "nameEn": "DR Congo",
    "nameEs": "Congo (Rep. Dem.)",
    "currencyCode": "CDF",
    "currencySymbol": "FC",
    "currencyNameEn": "Congolese franc",
    "currencyNameEs": "Congolese franc"
  },
  {
    "code": "EG",
    "nameEn": "Egypt",
    "nameEs": "Egipto",
    "currencyCode": "EGP",
    "currencySymbol": "£",
    "currencyNameEn": "Egyptian pound",
    "currencyNameEs": "Egyptian pound"
  },
  {
    "code": "GQ",
    "nameEn": "Equatorial Guinea",
    "nameEs": "Guinea Ecuatorial",
    "currencyCode": "XAF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Central African CFA franc",
    "currencyNameEs": "Central African CFA franc"
  },
  {
    "code": "ER",
    "nameEn": "Eritrea",
    "nameEs": "Eritrea",
    "currencyCode": "ERN",
    "currencySymbol": "Nfk",
    "currencyNameEn": "Eritrean nakfa",
    "currencyNameEs": "Eritrean nakfa"
  },
  {
    "code": "EE",
    "nameEn": "Estonia",
    "nameEs": "Estonia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "SZ",
    "nameEn": "Eswatini",
    "nameEs": "Suazilandia",
    "currencyCode": "SZL",
    "currencySymbol": "L",
    "currencyNameEn": "Swazi lilangeni",
    "currencyNameEs": "Swazi lilangeni"
  },
  {
    "code": "ET",
    "nameEn": "Ethiopia",
    "nameEs": "Etiopía",
    "currencyCode": "ETB",
    "currencySymbol": "Br",
    "currencyNameEn": "Ethiopian birr",
    "currencyNameEs": "Ethiopian birr"
  },
  {
    "code": "FK",
    "nameEn": "Falkland Islands",
    "nameEs": "Islas Malvinas",
    "currencyCode": "FKP",
    "currencySymbol": "£",
    "currencyNameEn": "Falkland Islands pound",
    "currencyNameEs": "Falkland Islands pound"
  },
  {
    "code": "FO",
    "nameEn": "Faroe Islands",
    "nameEs": "Islas Faroe",
    "currencyCode": "DKK",
    "currencySymbol": "kr",
    "currencyNameEn": "Danish krone",
    "currencyNameEs": "Danish krone"
  },
  {
    "code": "FJ",
    "nameEn": "Fiji",
    "nameEs": "Fiyi",
    "currencyCode": "FJD",
    "currencySymbol": "$",
    "currencyNameEn": "Fijian dollar",
    "currencyNameEs": "Fijian dollar"
  },
  {
    "code": "FI",
    "nameEn": "Finland",
    "nameEs": "Finlandia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "FR",
    "nameEn": "France",
    "nameEs": "Francia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "GF",
    "nameEn": "French Guiana",
    "nameEs": "Guayana Francesa",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "PF",
    "nameEn": "French Polynesia",
    "nameEs": "Polinesia Francesa",
    "currencyCode": "XPF",
    "currencySymbol": "₣",
    "currencyNameEn": "CFP franc",
    "currencyNameEs": "CFP franc"
  },
  {
    "code": "TF",
    "nameEn": "French Southern and Antarctic Lands",
    "nameEs": "Tierras Australes y Antárticas Francesas",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "GA",
    "nameEn": "Gabon",
    "nameEs": "Gabón",
    "currencyCode": "XAF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Central African CFA franc",
    "currencyNameEs": "Central African CFA franc"
  },
  {
    "code": "GM",
    "nameEn": "Gambia",
    "nameEs": "Gambia",
    "currencyCode": "GMD",
    "currencySymbol": "D",
    "currencyNameEn": "dalasi",
    "currencyNameEs": "dalasi"
  },
  {
    "code": "GE",
    "nameEn": "Georgia",
    "nameEs": "Georgia",
    "currencyCode": "GEL",
    "currencySymbol": "₾",
    "currencyNameEn": "lari",
    "currencyNameEs": "lari"
  },
  {
    "code": "DE",
    "nameEn": "Germany",
    "nameEs": "Alemania",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "GH",
    "nameEn": "Ghana",
    "nameEs": "Ghana",
    "currencyCode": "GHS",
    "currencySymbol": "₵",
    "currencyNameEn": "Ghanaian cedi",
    "currencyNameEs": "Ghanaian cedi"
  },
  {
    "code": "GI",
    "nameEn": "Gibraltar",
    "nameEs": "Gibraltar",
    "currencyCode": "GIP",
    "currencySymbol": "£",
    "currencyNameEn": "Gibraltar pound",
    "currencyNameEs": "Gibraltar pound"
  },
  {
    "code": "GR",
    "nameEn": "Greece",
    "nameEs": "Grecia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "GL",
    "nameEn": "Greenland",
    "nameEs": "Groenlandia",
    "currencyCode": "DKK",
    "currencySymbol": "kr.",
    "currencyNameEn": "krone",
    "currencyNameEs": "krone"
  },
  {
    "code": "GD",
    "nameEn": "Grenada",
    "nameEs": "Grenada",
    "currencyCode": "XCD",
    "currencySymbol": "$",
    "currencyNameEn": "Eastern Caribbean dollar",
    "currencyNameEs": "Eastern Caribbean dollar"
  },
  {
    "code": "GP",
    "nameEn": "Guadeloupe",
    "nameEs": "Guadalupe",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "GU",
    "nameEn": "Guam",
    "nameEs": "Guam",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "GG",
    "nameEn": "Guernsey",
    "nameEs": "Guernsey",
    "currencyCode": "GBP",
    "currencySymbol": "£",
    "currencyNameEn": "British pound",
    "currencyNameEs": "British pound"
  },
  {
    "code": "GN",
    "nameEn": "Guinea",
    "nameEs": "Guinea",
    "currencyCode": "GNF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Guinean franc",
    "currencyNameEs": "Guinean franc"
  },
  {
    "code": "GW",
    "nameEn": "Guinea-Bissau",
    "nameEs": "Guinea-Bisáu",
    "currencyCode": "XOF",
    "currencySymbol": "Fr",
    "currencyNameEn": "West African CFA franc",
    "currencyNameEs": "West African CFA franc"
  },
  {
    "code": "GY",
    "nameEn": "Guyana",
    "nameEs": "Guyana",
    "currencyCode": "GYD",
    "currencySymbol": "$",
    "currencyNameEn": "Guyanese dollar",
    "currencyNameEs": "Guyanese dollar"
  },
  {
    "code": "HT",
    "nameEn": "Haiti",
    "nameEs": "Haití",
    "currencyCode": "HTG",
    "currencySymbol": "G",
    "currencyNameEn": "Haitian gourde",
    "currencyNameEs": "Haitian gourde"
  },
  {
    "code": "HM",
    "nameEn": "Heard Island and McDonald Islands",
    "nameEs": "Islas Heard y McDonald",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "US Dollar",
    "currencyNameEs": "Dólar estadounidense"
  },
  {
    "code": "HK",
    "nameEn": "Hong Kong",
    "nameEs": "Hong Kong",
    "currencyCode": "HKD",
    "currencySymbol": "$",
    "currencyNameEn": "Hong Kong dollar",
    "currencyNameEs": "Hong Kong dollar"
  },
  {
    "code": "HU",
    "nameEn": "Hungary",
    "nameEs": "Hungría",
    "currencyCode": "HUF",
    "currencySymbol": "Ft",
    "currencyNameEn": "Hungarian forint",
    "currencyNameEs": "Hungarian forint"
  },
  {
    "code": "IS",
    "nameEn": "Iceland",
    "nameEs": "Islandia",
    "currencyCode": "ISK",
    "currencySymbol": "kr",
    "currencyNameEn": "Icelandic króna",
    "currencyNameEs": "Icelandic króna"
  },
  {
    "code": "IN",
    "nameEn": "India",
    "nameEs": "India",
    "currencyCode": "INR",
    "currencySymbol": "₹",
    "currencyNameEn": "Indian rupee",
    "currencyNameEs": "Indian rupee"
  },
  {
    "code": "ID",
    "nameEn": "Indonesia",
    "nameEs": "Indonesia",
    "currencyCode": "IDR",
    "currencySymbol": "Rp",
    "currencyNameEn": "Indonesian rupiah",
    "currencyNameEs": "Indonesian rupiah"
  },
  {
    "code": "IR",
    "nameEn": "Iran",
    "nameEs": "Iran",
    "currencyCode": "IRR",
    "currencySymbol": "﷼",
    "currencyNameEn": "Iranian rial",
    "currencyNameEs": "Iranian rial"
  },
  {
    "code": "IQ",
    "nameEn": "Iraq",
    "nameEs": "Irak",
    "currencyCode": "IQD",
    "currencySymbol": "ع.د",
    "currencyNameEn": "Iraqi dinar",
    "currencyNameEs": "Iraqi dinar"
  },
  {
    "code": "IE",
    "nameEn": "Ireland",
    "nameEs": "Irlanda",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "IM",
    "nameEn": "Isle of Man",
    "nameEs": "Isla de Man",
    "currencyCode": "GBP",
    "currencySymbol": "£",
    "currencyNameEn": "British pound",
    "currencyNameEs": "British pound"
  },
  {
    "code": "IL",
    "nameEn": "Israel",
    "nameEs": "Israel",
    "currencyCode": "ILS",
    "currencySymbol": "₪",
    "currencyNameEn": "Israeli new shekel",
    "currencyNameEs": "Israeli new shekel"
  },
  {
    "code": "IT",
    "nameEn": "Italy",
    "nameEs": "Italia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "CI",
    "nameEn": "Ivory Coast",
    "nameEs": "Costa de Marfil",
    "currencyCode": "XOF",
    "currencySymbol": "Fr",
    "currencyNameEn": "West African CFA franc",
    "currencyNameEs": "West African CFA franc"
  },
  {
    "code": "JM",
    "nameEn": "Jamaica",
    "nameEs": "Jamaica",
    "currencyCode": "JMD",
    "currencySymbol": "$",
    "currencyNameEn": "Jamaican dollar",
    "currencyNameEs": "Jamaican dollar"
  },
  {
    "code": "JP",
    "nameEn": "Japan",
    "nameEs": "Japón",
    "currencyCode": "JPY",
    "currencySymbol": "¥",
    "currencyNameEn": "Japanese yen",
    "currencyNameEs": "Japanese yen"
  },
  {
    "code": "JE",
    "nameEn": "Jersey",
    "nameEs": "Jersey",
    "currencyCode": "GBP",
    "currencySymbol": "£",
    "currencyNameEn": "British pound",
    "currencyNameEs": "British pound"
  },
  {
    "code": "JO",
    "nameEn": "Jordan",
    "nameEs": "Jordania",
    "currencyCode": "JOD",
    "currencySymbol": "د.ا",
    "currencyNameEn": "Jordanian dinar",
    "currencyNameEs": "Jordanian dinar"
  },
  {
    "code": "KZ",
    "nameEn": "Kazakhstan",
    "nameEs": "Kazajistán",
    "currencyCode": "KZT",
    "currencySymbol": "₸",
    "currencyNameEn": "Kazakhstani tenge",
    "currencyNameEs": "Kazakhstani tenge"
  },
  {
    "code": "KE",
    "nameEn": "Kenya",
    "nameEs": "Kenia",
    "currencyCode": "KES",
    "currencySymbol": "Sh",
    "currencyNameEn": "Kenyan shilling",
    "currencyNameEs": "Kenyan shilling"
  },
  {
    "code": "KI",
    "nameEn": "Kiribati",
    "nameEs": "Kiribati",
    "currencyCode": "AUD",
    "currencySymbol": "$",
    "currencyNameEn": "Australian dollar",
    "currencyNameEs": "Australian dollar"
  },
  {
    "code": "XK",
    "nameEn": "Kosovo",
    "nameEs": "Kosovo",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "KW",
    "nameEn": "Kuwait",
    "nameEs": "Kuwait",
    "currencyCode": "KWD",
    "currencySymbol": "د.ك",
    "currencyNameEn": "Kuwaiti dinar",
    "currencyNameEs": "Kuwaiti dinar"
  },
  {
    "code": "KG",
    "nameEn": "Kyrgyzstan",
    "nameEs": "Kirguizistán",
    "currencyCode": "KGS",
    "currencySymbol": "с",
    "currencyNameEn": "Kyrgyzstani som",
    "currencyNameEs": "Kyrgyzstani som"
  },
  {
    "code": "LA",
    "nameEn": "Laos",
    "nameEs": "Laos",
    "currencyCode": "LAK",
    "currencySymbol": "₭",
    "currencyNameEn": "Lao kip",
    "currencyNameEs": "Lao kip"
  },
  {
    "code": "LV",
    "nameEn": "Latvia",
    "nameEs": "Letonia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "LB",
    "nameEn": "Lebanon",
    "nameEs": "Líbano",
    "currencyCode": "LBP",
    "currencySymbol": "ل.ل",
    "currencyNameEn": "Lebanese pound",
    "currencyNameEs": "Lebanese pound"
  },
  {
    "code": "LS",
    "nameEn": "Lesotho",
    "nameEs": "Lesotho",
    "currencyCode": "LSL",
    "currencySymbol": "L",
    "currencyNameEn": "Lesotho loti",
    "currencyNameEs": "Lesotho loti"
  },
  {
    "code": "LR",
    "nameEn": "Liberia",
    "nameEs": "Liberia",
    "currencyCode": "LRD",
    "currencySymbol": "$",
    "currencyNameEn": "Liberian dollar",
    "currencyNameEs": "Liberian dollar"
  },
  {
    "code": "LY",
    "nameEn": "Libya",
    "nameEs": "Libia",
    "currencyCode": "LYD",
    "currencySymbol": "ل.د",
    "currencyNameEn": "Libyan dinar",
    "currencyNameEs": "Libyan dinar"
  },
  {
    "code": "LI",
    "nameEn": "Liechtenstein",
    "nameEs": "Liechtenstein",
    "currencyCode": "CHF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Swiss franc",
    "currencyNameEs": "Swiss franc"
  },
  {
    "code": "LT",
    "nameEn": "Lithuania",
    "nameEs": "Lituania",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "LU",
    "nameEn": "Luxembourg",
    "nameEs": "Luxemburgo",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "MO",
    "nameEn": "Macau",
    "nameEs": "Macao",
    "currencyCode": "MOP",
    "currencySymbol": "P",
    "currencyNameEn": "Macanese pataca",
    "currencyNameEs": "Macanese pataca"
  },
  {
    "code": "MG",
    "nameEn": "Madagascar",
    "nameEs": "Madagascar",
    "currencyCode": "MGA",
    "currencySymbol": "Ar",
    "currencyNameEn": "Malagasy ariary",
    "currencyNameEs": "Malagasy ariary"
  },
  {
    "code": "MW",
    "nameEn": "Malawi",
    "nameEs": "Malawi",
    "currencyCode": "MWK",
    "currencySymbol": "MK",
    "currencyNameEn": "Malawian kwacha",
    "currencyNameEs": "Malawian kwacha"
  },
  {
    "code": "MY",
    "nameEn": "Malaysia",
    "nameEs": "Malasia",
    "currencyCode": "MYR",
    "currencySymbol": "RM",
    "currencyNameEn": "Malaysian ringgit",
    "currencyNameEs": "Malaysian ringgit"
  },
  {
    "code": "MV",
    "nameEn": "Maldives",
    "nameEs": "Maldivas",
    "currencyCode": "MVR",
    "currencySymbol": ".ރ",
    "currencyNameEn": "Maldivian rufiyaa",
    "currencyNameEs": "Maldivian rufiyaa"
  },
  {
    "code": "ML",
    "nameEn": "Mali",
    "nameEs": "Mali",
    "currencyCode": "XOF",
    "currencySymbol": "Fr",
    "currencyNameEn": "West African CFA franc",
    "currencyNameEs": "West African CFA franc"
  },
  {
    "code": "MT",
    "nameEn": "Malta",
    "nameEs": "Malta",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "MH",
    "nameEn": "Marshall Islands",
    "nameEs": "Islas Marshall",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "MQ",
    "nameEn": "Martinique",
    "nameEs": "Martinica",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "MR",
    "nameEn": "Mauritania",
    "nameEs": "Mauritania",
    "currencyCode": "MRU",
    "currencySymbol": "UM",
    "currencyNameEn": "Mauritanian ouguiya",
    "currencyNameEs": "Mauritanian ouguiya"
  },
  {
    "code": "MU",
    "nameEn": "Mauritius",
    "nameEs": "Mauricio",
    "currencyCode": "MUR",
    "currencySymbol": "₨",
    "currencyNameEn": "Mauritian rupee",
    "currencyNameEs": "Mauritian rupee"
  },
  {
    "code": "YT",
    "nameEn": "Mayotte",
    "nameEs": "Mayotte",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "FM",
    "nameEn": "Micronesia",
    "nameEs": "Micronesia",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "MD",
    "nameEn": "Moldova",
    "nameEs": "Moldavia",
    "currencyCode": "MDL",
    "currencySymbol": "L",
    "currencyNameEn": "Moldovan leu",
    "currencyNameEs": "Moldovan leu"
  },
  {
    "code": "MC",
    "nameEn": "Monaco",
    "nameEs": "Mónaco",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "MN",
    "nameEn": "Mongolia",
    "nameEs": "Mongolia",
    "currencyCode": "MNT",
    "currencySymbol": "₮",
    "currencyNameEn": "Mongolian tögrög",
    "currencyNameEs": "Mongolian tögrög"
  },
  {
    "code": "ME",
    "nameEn": "Montenegro",
    "nameEs": "Montenegro",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "MS",
    "nameEn": "Montserrat",
    "nameEs": "Montserrat",
    "currencyCode": "XCD",
    "currencySymbol": "$",
    "currencyNameEn": "Eastern Caribbean dollar",
    "currencyNameEs": "Eastern Caribbean dollar"
  },
  {
    "code": "MA",
    "nameEn": "Morocco",
    "nameEs": "Marruecos",
    "currencyCode": "MAD",
    "currencySymbol": "د.م.",
    "currencyNameEn": "Moroccan dirham",
    "currencyNameEs": "Moroccan dirham"
  },
  {
    "code": "MZ",
    "nameEn": "Mozambique",
    "nameEs": "Mozambique",
    "currencyCode": "MZN",
    "currencySymbol": "MT",
    "currencyNameEn": "Mozambican metical",
    "currencyNameEs": "Mozambican metical"
  },
  {
    "code": "MM",
    "nameEn": "Myanmar",
    "nameEs": "Myanmar",
    "currencyCode": "MMK",
    "currencySymbol": "Ks",
    "currencyNameEn": "Burmese kyat",
    "currencyNameEs": "Burmese kyat"
  },
  {
    "code": "NA",
    "nameEn": "Namibia",
    "nameEs": "Namibia",
    "currencyCode": "NAD",
    "currencySymbol": "$",
    "currencyNameEn": "Namibian dollar",
    "currencyNameEs": "Namibian dollar"
  },
  {
    "code": "NR",
    "nameEn": "Nauru",
    "nameEs": "Nauru",
    "currencyCode": "AUD",
    "currencySymbol": "$",
    "currencyNameEn": "Australian dollar",
    "currencyNameEs": "Australian dollar"
  },
  {
    "code": "NP",
    "nameEn": "Nepal",
    "nameEs": "Nepal",
    "currencyCode": "NPR",
    "currencySymbol": "₨",
    "currencyNameEn": "Nepalese rupee",
    "currencyNameEs": "Nepalese rupee"
  },
  {
    "code": "NL",
    "nameEn": "Netherlands",
    "nameEs": "Países Bajos",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "NC",
    "nameEn": "New Caledonia",
    "nameEs": "Nueva Caledonia",
    "currencyCode": "XPF",
    "currencySymbol": "₣",
    "currencyNameEn": "CFP franc",
    "currencyNameEs": "CFP franc"
  },
  {
    "code": "NZ",
    "nameEn": "New Zealand",
    "nameEs": "Nueva Zelanda",
    "currencyCode": "NZD",
    "currencySymbol": "$",
    "currencyNameEn": "New Zealand dollar",
    "currencyNameEs": "New Zealand dollar"
  },
  {
    "code": "NE",
    "nameEn": "Niger",
    "nameEs": "Níger",
    "currencyCode": "XOF",
    "currencySymbol": "Fr",
    "currencyNameEn": "West African CFA franc",
    "currencyNameEs": "West African CFA franc"
  },
  {
    "code": "NG",
    "nameEn": "Nigeria",
    "nameEs": "Nigeria",
    "currencyCode": "NGN",
    "currencySymbol": "₦",
    "currencyNameEn": "Nigerian naira",
    "currencyNameEs": "Nigerian naira"
  },
  {
    "code": "NU",
    "nameEn": "Niue",
    "nameEs": "Niue",
    "currencyCode": "NZD",
    "currencySymbol": "$",
    "currencyNameEn": "New Zealand dollar",
    "currencyNameEs": "New Zealand dollar"
  },
  {
    "code": "NF",
    "nameEn": "Norfolk Island",
    "nameEs": "Isla de Norfolk",
    "currencyCode": "AUD",
    "currencySymbol": "$",
    "currencyNameEn": "Australian dollar",
    "currencyNameEs": "Australian dollar"
  },
  {
    "code": "KP",
    "nameEn": "North Korea",
    "nameEs": "Corea del Norte",
    "currencyCode": "KPW",
    "currencySymbol": "₩",
    "currencyNameEn": "North Korean won",
    "currencyNameEs": "North Korean won"
  },
  {
    "code": "MK",
    "nameEn": "North Macedonia",
    "nameEs": "Macedonia del Norte",
    "currencyCode": "MKD",
    "currencySymbol": "den",
    "currencyNameEn": "denar",
    "currencyNameEs": "denar"
  },
  {
    "code": "MP",
    "nameEn": "Northern Mariana Islands",
    "nameEs": "Islas Marianas del Norte",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "NO",
    "nameEn": "Norway",
    "nameEs": "Noruega",
    "currencyCode": "NOK",
    "currencySymbol": "kr",
    "currencyNameEn": "Norwegian krone",
    "currencyNameEs": "Norwegian krone"
  },
  {
    "code": "OM",
    "nameEn": "Oman",
    "nameEs": "Omán",
    "currencyCode": "OMR",
    "currencySymbol": "ر.ع.",
    "currencyNameEn": "Omani rial",
    "currencyNameEs": "Omani rial"
  },
  {
    "code": "PK",
    "nameEn": "Pakistan",
    "nameEs": "Pakistán",
    "currencyCode": "PKR",
    "currencySymbol": "₨",
    "currencyNameEn": "Pakistani rupee",
    "currencyNameEs": "Pakistani rupee"
  },
  {
    "code": "PW",
    "nameEn": "Palau",
    "nameEs": "Palau",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "PS",
    "nameEn": "Palestine",
    "nameEs": "Palestina",
    "currencyCode": "EGP",
    "currencySymbol": "E£",
    "currencyNameEn": "Egyptian pound",
    "currencyNameEs": "Egyptian pound"
  },
  {
    "code": "PG",
    "nameEn": "Papua New Guinea",
    "nameEs": "Papúa Nueva Guinea",
    "currencyCode": "PGK",
    "currencySymbol": "K",
    "currencyNameEn": "Papua New Guinean kina",
    "currencyNameEs": "Papua New Guinean kina"
  },
  {
    "code": "PH",
    "nameEn": "Philippines",
    "nameEs": "Filipinas",
    "currencyCode": "PHP",
    "currencySymbol": "₱",
    "currencyNameEn": "Philippine peso",
    "currencyNameEs": "Philippine peso"
  },
  {
    "code": "PN",
    "nameEn": "Pitcairn Islands",
    "nameEs": "Islas Pitcairn",
    "currencyCode": "NZD",
    "currencySymbol": "$",
    "currencyNameEn": "New Zealand dollar",
    "currencyNameEs": "New Zealand dollar"
  },
  {
    "code": "PL",
    "nameEn": "Poland",
    "nameEs": "Polonia",
    "currencyCode": "PLN",
    "currencySymbol": "zł",
    "currencyNameEn": "Polish złoty",
    "currencyNameEs": "Polish złoty"
  },
  {
    "code": "PT",
    "nameEn": "Portugal",
    "nameEs": "Portugal",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "QA",
    "nameEn": "Qatar",
    "nameEs": "Catar",
    "currencyCode": "QAR",
    "currencySymbol": "ر.ق",
    "currencyNameEn": "Qatari riyal",
    "currencyNameEs": "Qatari riyal"
  },
  {
    "code": "CG",
    "nameEn": "Republic of the Congo",
    "nameEs": "Congo",
    "currencyCode": "XAF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Central African CFA franc",
    "currencyNameEs": "Central African CFA franc"
  },
  {
    "code": "RE",
    "nameEn": "Réunion",
    "nameEs": "Reunión",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "RO",
    "nameEn": "Romania",
    "nameEs": "Rumania",
    "currencyCode": "RON",
    "currencySymbol": "lei",
    "currencyNameEn": "Romanian leu",
    "currencyNameEs": "Romanian leu"
  },
  {
    "code": "RU",
    "nameEn": "Russia",
    "nameEs": "Rusia",
    "currencyCode": "RUB",
    "currencySymbol": "₽",
    "currencyNameEn": "Russian ruble",
    "currencyNameEs": "Russian ruble"
  },
  {
    "code": "RW",
    "nameEn": "Rwanda",
    "nameEs": "Ruanda",
    "currencyCode": "RWF",
    "currencySymbol": "Fr",
    "currencyNameEn": "Rwandan franc",
    "currencyNameEs": "Rwandan franc"
  },
  {
    "code": "BL",
    "nameEn": "Saint Barthélemy",
    "nameEs": "San Bartolomé",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "SH",
    "nameEn": "Saint Helena, Ascension and Tristan da Cunha",
    "nameEs": "Santa Elena, Ascensión y Tristán de Acuña",
    "currencyCode": "GBP",
    "currencySymbol": "£",
    "currencyNameEn": "Pound sterling",
    "currencyNameEs": "Pound sterling"
  },
  {
    "code": "KN",
    "nameEn": "Saint Kitts and Nevis",
    "nameEs": "San Cristóbal y Nieves",
    "currencyCode": "XCD",
    "currencySymbol": "$",
    "currencyNameEn": "Eastern Caribbean dollar",
    "currencyNameEs": "Eastern Caribbean dollar"
  },
  {
    "code": "LC",
    "nameEn": "Saint Lucia",
    "nameEs": "Santa Lucía",
    "currencyCode": "XCD",
    "currencySymbol": "$",
    "currencyNameEn": "Eastern Caribbean dollar",
    "currencyNameEs": "Eastern Caribbean dollar"
  },
  {
    "code": "MF",
    "nameEn": "Saint Martin",
    "nameEs": "Saint Martin",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "PM",
    "nameEn": "Saint Pierre and Miquelon",
    "nameEs": "San Pedro y Miquelón",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "VC",
    "nameEn": "Saint Vincent and the Grenadines",
    "nameEs": "San Vicente y Granadinas",
    "currencyCode": "XCD",
    "currencySymbol": "$",
    "currencyNameEn": "Eastern Caribbean dollar",
    "currencyNameEs": "Eastern Caribbean dollar"
  },
  {
    "code": "WS",
    "nameEn": "Samoa",
    "nameEs": "Samoa",
    "currencyCode": "WST",
    "currencySymbol": "T",
    "currencyNameEn": "Samoan tālā",
    "currencyNameEs": "Samoan tālā"
  },
  {
    "code": "SM",
    "nameEn": "San Marino",
    "nameEs": "San Marino",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "ST",
    "nameEn": "São Tomé and Príncipe",
    "nameEs": "Santo Tomé y Príncipe",
    "currencyCode": "STN",
    "currencySymbol": "Db",
    "currencyNameEn": "São Tomé and Príncipe dobra",
    "currencyNameEs": "São Tomé and Príncipe dobra"
  },
  {
    "code": "SA",
    "nameEn": "Saudi Arabia",
    "nameEs": "Arabia Saudí",
    "currencyCode": "SAR",
    "currencySymbol": "ر.س",
    "currencyNameEn": "Saudi riyal",
    "currencyNameEs": "Saudi riyal"
  },
  {
    "code": "SN",
    "nameEn": "Senegal",
    "nameEs": "Senegal",
    "currencyCode": "XOF",
    "currencySymbol": "Fr",
    "currencyNameEn": "West African CFA franc",
    "currencyNameEs": "West African CFA franc"
  },
  {
    "code": "RS",
    "nameEn": "Serbia",
    "nameEs": "Serbia",
    "currencyCode": "RSD",
    "currencySymbol": "дин.",
    "currencyNameEn": "Serbian dinar",
    "currencyNameEs": "Serbian dinar"
  },
  {
    "code": "SC",
    "nameEn": "Seychelles",
    "nameEs": "Seychelles",
    "currencyCode": "SCR",
    "currencySymbol": "₨",
    "currencyNameEn": "Seychellois rupee",
    "currencyNameEs": "Seychellois rupee"
  },
  {
    "code": "SL",
    "nameEn": "Sierra Leone",
    "nameEs": "Sierra Leone",
    "currencyCode": "SLE",
    "currencySymbol": "Le",
    "currencyNameEn": "Leone",
    "currencyNameEs": "Leone"
  },
  {
    "code": "SG",
    "nameEn": "Singapore",
    "nameEs": "Singapur",
    "currencyCode": "SGD",
    "currencySymbol": "$",
    "currencyNameEn": "Singapore dollar",
    "currencyNameEs": "Singapore dollar"
  },
  {
    "code": "SX",
    "nameEn": "Sint Maarten",
    "nameEs": "Sint Maarten",
    "currencyCode": "ANG",
    "currencySymbol": "ƒ",
    "currencyNameEn": "Netherlands Antillean guilder",
    "currencyNameEs": "Netherlands Antillean guilder"
  },
  {
    "code": "SK",
    "nameEn": "Slovakia",
    "nameEs": "República Eslovaca",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "SI",
    "nameEn": "Slovenia",
    "nameEs": "Eslovenia",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "SB",
    "nameEn": "Solomon Islands",
    "nameEs": "Islas Salomón",
    "currencyCode": "SBD",
    "currencySymbol": "$",
    "currencyNameEn": "Solomon Islands dollar",
    "currencyNameEs": "Solomon Islands dollar"
  },
  {
    "code": "SO",
    "nameEn": "Somalia",
    "nameEs": "Somalia",
    "currencyCode": "SOS",
    "currencySymbol": "Sh",
    "currencyNameEn": "Somali shilling",
    "currencyNameEs": "Somali shilling"
  },
  {
    "code": "ZA",
    "nameEn": "South Africa",
    "nameEs": "Sudáfrica",
    "currencyCode": "ZAR",
    "currencySymbol": "R",
    "currencyNameEn": "South African rand",
    "currencyNameEs": "South African rand"
  },
  {
    "code": "GS",
    "nameEn": "South Georgia",
    "nameEs": "Islas Georgias del Sur y Sandwich del Sur",
    "currencyCode": "GBP",
    "currencySymbol": "£",
    "currencyNameEn": "British pound",
    "currencyNameEs": "British pound"
  },
  {
    "code": "KR",
    "nameEn": "South Korea",
    "nameEs": "Corea del Sur",
    "currencyCode": "KRW",
    "currencySymbol": "₩",
    "currencyNameEn": "South Korean won",
    "currencyNameEs": "South Korean won"
  },
  {
    "code": "SS",
    "nameEn": "South Sudan",
    "nameEs": "Sudán del Sur",
    "currencyCode": "SSP",
    "currencySymbol": "£",
    "currencyNameEn": "South Sudanese pound",
    "currencyNameEs": "South Sudanese pound"
  },
  {
    "code": "LK",
    "nameEn": "Sri Lanka",
    "nameEs": "Sri Lanka",
    "currencyCode": "LKR",
    "currencySymbol": "Rs  රු",
    "currencyNameEn": "Sri Lankan rupee",
    "currencyNameEs": "Sri Lankan rupee"
  },
  {
    "code": "SD",
    "nameEn": "Sudan",
    "nameEs": "Sudán",
    "currencyCode": "SDG",
    "currencySymbol": "ج.س",
    "currencyNameEn": "Sudanese pound",
    "currencyNameEs": "Sudanese pound"
  },
  {
    "code": "SR",
    "nameEn": "Suriname",
    "nameEs": "Surinam",
    "currencyCode": "SRD",
    "currencySymbol": "$",
    "currencyNameEn": "Surinamese dollar",
    "currencyNameEs": "Surinamese dollar"
  },
  {
    "code": "SJ",
    "nameEn": "Svalbard and Jan Mayen",
    "nameEs": "Islas Svalbard y Jan Mayen",
    "currencyCode": "NOK",
    "currencySymbol": "kr",
    "currencyNameEn": "krone",
    "currencyNameEs": "krone"
  },
  {
    "code": "SE",
    "nameEn": "Sweden",
    "nameEs": "Suecia",
    "currencyCode": "SEK",
    "currencySymbol": "kr",
    "currencyNameEn": "Swedish krona",
    "currencyNameEs": "Swedish krona"
  },
  {
    "code": "CH",
    "nameEn": "Switzerland",
    "nameEs": "Suiza",
    "currencyCode": "CHF",
    "currencySymbol": "Fr.",
    "currencyNameEn": "Swiss franc",
    "currencyNameEs": "Swiss franc"
  },
  {
    "code": "SY",
    "nameEn": "Syria",
    "nameEs": "Siria",
    "currencyCode": "SYP",
    "currencySymbol": "£",
    "currencyNameEn": "Syrian pound",
    "currencyNameEs": "Syrian pound"
  },
  {
    "code": "TW",
    "nameEn": "Taiwan",
    "nameEs": "Taiwán",
    "currencyCode": "TWD",
    "currencySymbol": "$",
    "currencyNameEn": "New Taiwan dollar",
    "currencyNameEs": "New Taiwan dollar"
  },
  {
    "code": "TJ",
    "nameEn": "Tajikistan",
    "nameEs": "Tayikistán",
    "currencyCode": "TJS",
    "currencySymbol": "ЅМ",
    "currencyNameEn": "Tajikistani somoni",
    "currencyNameEs": "Tajikistani somoni"
  },
  {
    "code": "TZ",
    "nameEn": "Tanzania",
    "nameEs": "Tanzania",
    "currencyCode": "TZS",
    "currencySymbol": "Sh",
    "currencyNameEn": "Tanzanian shilling",
    "currencyNameEs": "Tanzanian shilling"
  },
  {
    "code": "TH",
    "nameEn": "Thailand",
    "nameEs": "Tailandia",
    "currencyCode": "THB",
    "currencySymbol": "฿",
    "currencyNameEn": "Thai baht",
    "currencyNameEs": "Thai baht"
  },
  {
    "code": "TL",
    "nameEn": "Timor-Leste",
    "nameEs": "Timor Oriental",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "TG",
    "nameEn": "Togo",
    "nameEs": "Togo",
    "currencyCode": "XOF",
    "currencySymbol": "Fr",
    "currencyNameEn": "West African CFA franc",
    "currencyNameEs": "West African CFA franc"
  },
  {
    "code": "TK",
    "nameEn": "Tokelau",
    "nameEs": "Islas Tokelau",
    "currencyCode": "NZD",
    "currencySymbol": "$",
    "currencyNameEn": "New Zealand dollar",
    "currencyNameEs": "New Zealand dollar"
  },
  {
    "code": "TO",
    "nameEn": "Tonga",
    "nameEs": "Tonga",
    "currencyCode": "TOP",
    "currencySymbol": "T$",
    "currencyNameEn": "Tongan paʻanga",
    "currencyNameEs": "Tongan paʻanga"
  },
  {
    "code": "TT",
    "nameEn": "Trinidad and Tobago",
    "nameEs": "Trinidad y Tobago",
    "currencyCode": "TTD",
    "currencySymbol": "$",
    "currencyNameEn": "Trinidad and Tobago dollar",
    "currencyNameEs": "Trinidad and Tobago dollar"
  },
  {
    "code": "TN",
    "nameEn": "Tunisia",
    "nameEs": "Túnez",
    "currencyCode": "TND",
    "currencySymbol": "د.ت",
    "currencyNameEn": "Tunisian dinar",
    "currencyNameEs": "Tunisian dinar"
  },
  {
    "code": "TR",
    "nameEn": "Turkey",
    "nameEs": "Turquía",
    "currencyCode": "TRY",
    "currencySymbol": "₺",
    "currencyNameEn": "Turkish lira",
    "currencyNameEs": "Turkish lira"
  },
  {
    "code": "TM",
    "nameEn": "Turkmenistan",
    "nameEs": "Turkmenistán",
    "currencyCode": "TMT",
    "currencySymbol": "m",
    "currencyNameEn": "Turkmenistan manat",
    "currencyNameEs": "Turkmenistan manat"
  },
  {
    "code": "TC",
    "nameEn": "Turks and Caicos Islands",
    "nameEs": "Islas Turks y Caicos",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "TV",
    "nameEn": "Tuvalu",
    "nameEs": "Tuvalu",
    "currencyCode": "AUD",
    "currencySymbol": "$",
    "currencyNameEn": "Australian dollar",
    "currencyNameEs": "Australian dollar"
  },
  {
    "code": "UG",
    "nameEn": "Uganda",
    "nameEs": "Uganda",
    "currencyCode": "UGX",
    "currencySymbol": "Sh",
    "currencyNameEn": "Ugandan shilling",
    "currencyNameEs": "Ugandan shilling"
  },
  {
    "code": "UA",
    "nameEn": "Ukraine",
    "nameEs": "Ucrania",
    "currencyCode": "UAH",
    "currencySymbol": "₴",
    "currencyNameEn": "Ukrainian hryvnia",
    "currencyNameEs": "Ukrainian hryvnia"
  },
  {
    "code": "AE",
    "nameEn": "United Arab Emirates",
    "nameEs": "Emiratos Árabes Unidos",
    "currencyCode": "AED",
    "currencySymbol": "د.إ",
    "currencyNameEn": "United Arab Emirates dirham",
    "currencyNameEs": "United Arab Emirates dirham"
  },
  {
    "code": "GB",
    "nameEn": "United Kingdom",
    "nameEs": "Reino Unido",
    "currencyCode": "GBP",
    "currencySymbol": "£",
    "currencyNameEn": "British pound",
    "currencyNameEs": "British pound"
  },
  {
    "code": "UM",
    "nameEn": "United States Minor Outlying Islands",
    "nameEs": "Islas Ultramarinas Menores de Estados Unidos",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "VI",
    "nameEn": "United States Virgin Islands",
    "nameEs": "Islas Vírgenes de los Estados Unidos",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "currencyNameEn": "United States dollar",
    "currencyNameEs": "United States dollar"
  },
  {
    "code": "UZ",
    "nameEn": "Uzbekistan",
    "nameEs": "Uzbekistán",
    "currencyCode": "UZS",
    "currencySymbol": "so'm",
    "currencyNameEn": "Uzbekistani soʻm",
    "currencyNameEs": "Uzbekistani soʻm"
  },
  {
    "code": "VU",
    "nameEn": "Vanuatu",
    "nameEs": "Vanuatu",
    "currencyCode": "VUV",
    "currencySymbol": "Vt",
    "currencyNameEn": "Vanuatu vatu",
    "currencyNameEs": "Vanuatu vatu"
  },
  {
    "code": "VA",
    "nameEn": "Vatican City",
    "nameEs": "Ciudad del Vaticano",
    "currencyCode": "EUR",
    "currencySymbol": "€",
    "currencyNameEn": "euro",
    "currencyNameEs": "euro"
  },
  {
    "code": "VN",
    "nameEn": "Vietnam",
    "nameEs": "Vietnam",
    "currencyCode": "VND",
    "currencySymbol": "₫",
    "currencyNameEn": "Vietnamese đồng",
    "currencyNameEs": "Vietnamese đồng"
  },
  {
    "code": "WF",
    "nameEn": "Wallis and Futuna",
    "nameEs": "Wallis y Futuna",
    "currencyCode": "XPF",
    "currencySymbol": "₣",
    "currencyNameEn": "CFP franc",
    "currencyNameEs": "CFP franc"
  },
  {
    "code": "EH",
    "nameEn": "Western Sahara",
    "nameEs": "Sahara Occidental",
    "currencyCode": "DZD",
    "currencySymbol": "دج",
    "currencyNameEn": "Algerian dinar",
    "currencyNameEs": "Algerian dinar"
  },
  {
    "code": "YE",
    "nameEn": "Yemen",
    "nameEs": "Yemen",
    "currencyCode": "YER",
    "currencySymbol": "﷼",
    "currencyNameEn": "Yemeni rial",
    "currencyNameEs": "Yemeni rial"
  },
  {
    "code": "ZM",
    "nameEn": "Zambia",
    "nameEs": "Zambia",
    "currencyCode": "ZMW",
    "currencySymbol": "ZK",
    "currencyNameEn": "Zambian kwacha",
    "currencyNameEs": "Zambian kwacha"
  },
  {
    "code": "ZW",
    "nameEn": "Zimbabwe",
    "nameEs": "Zimbabue",
    "currencyCode": "ZWL",
    "currencySymbol": "$",
    "currencyNameEn": "Zimbabwean dollar",
    "currencyNameEs": "Zimbabwean dollar"
  }
];

export const PRIORITY_COUNTRY_CODES = ["US","MX","PR","HN","CO","VE","GT","SV","DO","CU","PE","CL","AR","BO","EC","CR","PA","PY","UY","NI","ES","BR","CA"] as const;

const byCode = new Map(COUNTRIES.map((c) => [c.code, c]));

export function getCountryByCode(code: string | null | undefined): CountryRecord | undefined {
  if (!code) return undefined;
  return byCode.get(code.toUpperCase());
}

/** Priority countries first, then alphabetical by English name (excluding priority set). */
export function getCountriesSortedForSelect(): CountryRecord[] {
  return COUNTRIES;
}
